# Generated by Django 4.2.3 on 2023-07-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('commissioning_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindTurbineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('nominal_power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WindTurbine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('tower_height', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='known_turbines', to='api.windturbinemodel')),
                ('wind_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turbines', to='api.windfarm')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('wind_farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_meter', to='api.windfarm')),
            ],
        ),
    ]
